services:
  db:
    image: postgis/postgis:15-3.4-alpine
    restart: always
    expose:
      - 5432
    ports:
      - 5432:5432
    env_file:
      - vars.env
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -d ${POSTGRES_DB} -U ${POSTGRES_USER}"]
      with:
        password: ${POSTGRES_PASSWORD}
      interval: 5s
      timeout: 15s
      retries: 100

  server:
    build: ./server
    env_file:
      - vars.env
    healthcheck:
      test: 'curl --fail --request POST --header ''content-type: application/json'' --url ''http://localhost:5000'' --data ''{"query":"query { __typename }"}'' || exit 1'
      interval: 5s
      timeout: 5s
      retries: 10
    depends_on:
      db:
        condition: service_healthy

  client:
    build: ./client
    env_file: vars.env
    healthcheck:
      test: "curl --fail --request GET --url 'http://localhost:3000' || exit 1"
      interval: 5s
      timeout: 5s
      retries: 10
    depends_on:
      server:
        condition: service_healthy

  e2e:
    build: ./e2e
    volumes:
      - ./e2e/playwright-report:/app/playwright-report
      - ./e2e/test-results:/app/test-results
    depends_on:
      client:
        condition: service_healthy