services:
  server:
    build: ./server
    env_file:
      - vars.env
    ports:
      - 4000:4000
    volumes:
      - ./server/src:/app/src

  client:
    build: ./client
    ports:
      - 3000:3000
    volumes:
      - ./client/src:/app/src

  db:
    image: postgres
    restart: always
    env_file:
      - vars.env
    volumes:
      - postgres:/var/lib/postgresql/data

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080

volumes:
  postgres: