name: jest-and-docker-ci

on: push

jobs:
    checkout:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout code
              uses: actions/checkout@v3
    test-client:
        needs: checkout
        runs-on: ubuntu-latest
        steps:
            - name: Go to client and run tests
              run: cd client && npm i && npm test
    docker:
        needs: test-client
        if: github.base_ref == 'refs/heads/main'
        runs-on: ubuntu-latest
        steps:
            - name: Set up QEMU
              uses: docker/setup-qemu-action@v2
            - name: Set up Docker Buildx
              uses: docker/setup-buildx-action@v2
            - name: Login to Docker Hub
              uses: docker/login-action@v2
              with:
                username: ${{ secrets.DOCKERHUB_USERNAME }}
                password: ${{ secrets.DOCKERHUB_TOKEN }}
            - name: Build and push
              uses: docker/build-push-action@v4
              with:
                push: true
                context: "{{defaultContext}}:client"
                tags: ${{ secrets.DOCKERHUB_USERNAME }}/CityGuide:latest