name: deploy-ci

on: pull_request

jobs:
  client-unit-test:
    if: github.base_ref == 'main'
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
        working-directory: client
    steps:
      - name: Check out the code
        uses: actions/checkout@v3
      - name: Install npm dependencies
        run: npm install
      - name: Launch unit tests
        run: npm run unit-test

  docker:
    needs: client-unit-test
    runs-on: ubuntu-latest
    steps:
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build and push
        uses: docker/build-push-action@v4
        with:
          push: true
          context: "{{defaultContext}}:client"
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/cityguide:latest
