name: e2e tests

on:
  pull_request:
    branches: [ dev, staging ]

jobs:
  playwright:
    timeout-minutes: 30
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Node 18
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Set up environment variables
        env:
          JWT_SECRET_KEY: testjwt
          POSTGRES_PASSWORD: example
        run: |
          touch vars.env
          echo "JWT_SECRET_KEY=${JWT_SECRET_KEY}" >> vars.env
          echo "POSTGRES_PASSWORD=${POSTGRES_PASSWORD}" >> vars.env

      - name: Install dependencies with clean install
        run: npm ci

      - name: Install Playwright Browsers
        run: npx playwright install --with-deps

      - name: Run Playwright tests
        run: npm run e2e-test

      - uses: actions/upload-artifact@v3
        if: always()
        with:
          name: playwright-report
          path: playwright-report/
          retention-days: 30
