name: tests

on: pull_request

jobs:
  client-tests:
    if: github.base_ref == 'dev'
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
        working-directory: client
    steps:
      - name: Check out the code
        uses: actions/checkout@v3
      - name: Install npm dependencies
        run: npm install
      - name: Launch unit tests
        run: npm run test

  e2e-tests:
    if: github.base_ref == 'dev'
    runs-on: ubuntu-latest
    steps:
      - name: Check out the code
        uses: actions/checkout@v3
      - name: Run Playwright Tests
        uses: ./e2e/.github/workflows/playwright.yml
