name: unit-test

on: push

jobs:
  unit-test:
    runs-on: ubuntu-latest
    steps:
      - name: Check out the code
        uses: actions/checkout@v3
      - name: Install npm dependencies
        run: cd ./front && npm install
      - name: Launch unit tests
        run: npm run unit-test
